# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CTFLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('ctf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfboard.CTF')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cseaccountname', models.CharField(max_length=50)),
                ('pwnablekraccountname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WriteUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ctflevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfboard.CTFLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfboard.UserProfile')),
            ],
        ),
    ]
