# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfboard', '0002_userprofile_pwnablekrscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctflevel',
            name='flag',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
