# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfboard', '0005_auto_20170328_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='flag',
            field=models.TextField(default=False, max_length=100),
        ),
    ]
